#******************************************************************************
# Copyright (C) 2017 by Alex Fosdick - University of Colorado
#
# Redistribution, modification or use of this software in source or binary
# forms is permitted as long as the files maintain this copyright. Users are 
# permitted to modify this and use it to learn about the field of embedded
# software. Alex Fosdick and the University of Colorado are not liable for any
# misuse of this material. 
#
#*****************************************************************************

#------------------------------------------------------------------------------
# <Put a Description Here>
#
# Use: make [TARGET] [PLATFORM-OVERRIDES]
#
# Build Targets:
#      <Put a description of the supported targets here>
#
# Platform Overrides:
#      <Put a description of the supported Overrides here
#
#------------------------------------------------------------------------------
include sources.mk



# Platform Overrides
PLATFORM = 

	ifeq ($(PLATFORM),HOST)
		CC = <Add the appropriate compiler>
		# etc
	else
		CC = <Add the appropriate compiler>
		# etc
	endif

# General Flags for Both Platforms
FLAGS = -Wall \
		-Werror \
		-g \
		-O0 \
		-std=c99

# Architectures Specific Flags
LINKER_FILE = 
CPU = 
ARCH = 
SPECS = 

# Compiler Flags and Defines
CC = 
LD = 
TARGET = c1m2
LDFLAGS = 
CFLAGS = 
CPPFLAGs = 

